### ISSUE TITLE
Create Bots "GitHub Page"

### ISSUE THREAD

**Issue by JCapriotti** [bots-edi/bots-tmp#4]
Create this: 
http://skilchen.github.io/bots/

At this URL:
http://bots-edi.github.io

I plan to take a look at this. Please add feedback if you have any :)

**Comment by JCapriotti** [comment]
Added /docs repo and GitHub Pages repo yesterday. Leaving this open until I document it better.

**Comment by JCapriotti** [comment]
Added initial documentation about the docs.

**Comment by WouterVH** [comment]
great work!
